version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - VOTE1VALUE=Cats
      - VOTE2VALUE=Dogs
      - TITLE=Voting App
      - REDIS=redis
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    