name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit
          pip install -r azure-vote/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 azure-vote/main.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 azure-vote/main.py --count --max-complexity=10 --max-line-length=127 --statistics
     
      - name: Run flake8 security plugins
        uses: py-actions/flake8@v2
        with:
          path: azure-vote
          plugins: "flake8-bandit flake8-security"
          ignore: "S101"
      - name: Security check with bandit
        run: |
          bandit -r azure-vote/ -ll

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: ./azure-vote
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves #,recom #mendations,compare
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
          image: ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./azure-vote
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest
